# -*- coding: utf-8 -*-
"""
路径 UI 编辑器（pathkit.htmleditor）—— PathHTMLEditor 类
=========================================================

PathHTMLEditor: export a path as one self-contained HTML file you drag points in.

`PathEditor` 只能在 Python 里改坐标：改一次、出一张图、看一眼，再改。
本类补上「手」——把同一条路径导出成**一个自我包含的 .html**，
用鼠标拖锚点与调整杆，右侧实时给出 d 串和可直接粘贴的 malight 代码。

导出的页面**零依赖、纯离线**（没有任何 CDN、框架或构建步骤），
双击就能用，也可以直接发给别人；页面里自带 中文 / English 切换。

三种用法:

1. **改一条已有路径**
   ``p = pen.path(...)`` 画好 → ``PathHTMLEditor(p).save("edit.html")``。
2. **从 d 串开始**
   ``PathHTMLEditor(d="M20,200 C80,40 180,40 240,200").save("edit.html")``。
3. **接着 Python 的进度改**（配合 `PathEditor`）
   ``ed.save_json("points.json")`` 存档 → 页面里拖 → 下载回 points.json
   → ``ed.load_json("points.json")`` 读回。
   页面下载的 JSON 与 `PathEditor.to_dict()` **同一套结构**，可以直接读回。

页面能做什么 / 不能做什么:

* 能：拖锚点、拖调整点、「锚点连动调整杆」开关、双击某段在中点插入锚点、
  方向键微调（Shift 走 10 像素）、复位、下载点位 JSON、复制 d 串与代码。
* 不能：拖完之后**回写**正在运行的 Python 进程（浏览器里改的只是页面自己的数据）。
  要闭环就走上面第 3 种用法，用 JSON 往返。
* 圆弧段（A）不支持拆分锚点 —— 与 `PathSegment.split()` 的限制一致。

「锚点连动调整杆」勾上时，锚点位移多少、挂在它这一侧的调整杆就位移多少
（曲线不会突然拐个弯）—— 这正是 `PathEditor.move_anchor(..., link_handles=True)`；
取消勾选则只动锚点本身，与默认的 `move_anchor()` 一致。

页面里的 JS 与 Python 是**两份实现**：``tools/check_htmleditor_js.py`` 会把页面
那段 JS 抽出来用 Node 跑一遍，逐锚点确认两边拖出来的 d 串一模一样
（连动 / 不连动两种模式都比），并且脚本自带 ``--self-test`` —— 注入 8 处真实
错法，确认比对项不是「永远为空所以永远通过」。

主页面的 UI 文案取自 `malight.i18n` 的 ``html.*`` 词条，
导出时按 `use_language()` 取 en / zh 两套内嵌进页面，所以一份文件两种语言都能看。
"""

# ---------------------------------------------------------------------------
# 直接运行引导：在 PyCharm 里点绿色三角运行本文件（或命令行 python 本文件路径）时，
# 相对导入需要包上下文，这里自动补上项目根路径与包名。
# 正常 `import malight.xxx` 时这段不会执行，对包本身零影响。
# ---------------------------------------------------------------------------
if __name__ == "__main__" and not __package__:
    import os as _os
    import sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.dirname(
        _os.path.abspath(__file__)))))
    __package__ = "malight.pathkit"

import json
import os

from ..i18n import is_chinese, t, use_language
from ..tools import paint_path
from .parser import parse_path_d, segments_to_d


#: 页面里要用的全部标签词条（`i18n` 里 en / zh 两套都要配齐，否则页面会露出键名）
UI_KEYS = (
    "html.title", "html.subtitle", "html.hint",
    "html.segments", "html.anchors", "html.controls",
    "html.d_label", "html.code_label", "html.copy", "html.copied",
    "html.copy_fail", "html.reset", "html.handles", "html.link_handles",
    "html.json", "html.json_hint", "html.arc_no_split",
)


def _ui_messages() -> dict:
    """
    把 ``html.*`` 词条按语言取出来，供页面内切换。

    取词时用 ``use_language()`` 临时切语言，**不会污染全局设置**
    （这正是 `use_language` 存在的意义：文档生成与这里取两套文案都用它）。
    """
    out = {}
    for code in ("en", "zh"):
        with use_language(code):
            out[code] = {k.split(".", 1)[1]: t(k) for k in UI_KEYS}
    return out


# ===========================================================================
# 页面模板 / Page template
# ===========================================================================
# 用 @@TOKEN@@ 占位 + str.replace 注入，**不走 str.format** ——
# 页面里的 JS / CSS 到处是花括号，用 format 得把每一处都写成 {{ }}，改一处漏一处。
_PAGE = r"""<!DOCTYPE html>
<html lang="@@LANG@@">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@@TITLE@@</title>
<!-- Generated by malight.pathkit.PathHTMLEditor — do not edit by hand. -->
<style>
:root{--bg:#f4f4f6;--card:#fff;--ink:#1c1c1e;--muted:#6b6b70;--line:#dcdce1;
      --accent:#e63946;--anchor:#1f6feb;--ctrl:#d9822b}
*{box-sizing:border-box}
body{margin:0;padding:24px;background:var(--bg);color:var(--ink);
     font:14px/1.6 -apple-system,"Segoe UI","Microsoft YaHei",sans-serif}
h1{margin:0 0 4px;font-size:18px;font-weight:600}
.sub{color:var(--muted);margin:0 0 18px}
.wrap{display:flex;gap:20px;flex-wrap:wrap;align-items:flex-start}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px}
.stage{position:relative;flex:0 0 auto}
.side{flex:1 1 320px;min-width:300px;display:flex;flex-direction:column;gap:12px}
.stats{display:flex;gap:10px}
.stat{flex:1;background:var(--card);border:1px solid var(--line);
      border-radius:10px;padding:10px 12px}
.stat b{display:block;font-size:20px;font-weight:600;margin-top:2px}
.stat span{color:var(--muted);font-size:12px}
.row{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}
button{font:inherit;padding:6px 12px;border:1px solid var(--line);background:var(--card);
       color:var(--ink);border-radius:8px;cursor:pointer}
button:hover{border-color:var(--muted)}
button.on{background:var(--ink);color:var(--card);border-color:var(--ink)}
label.chk{display:flex;align-items:center;gap:6px;cursor:pointer;color:var(--muted)}
pre{background:var(--card);border:1px solid var(--line);border-radius:10px;
    padding:12px;margin:0;overflow:auto;font-size:12.5px;line-height:1.55;
    font-family:ui-monospace,Consolas,"Courier New",monospace;white-space:pre-wrap;
    word-break:break-all;max-height:270px}
.lbl{display:flex;justify-content:space-between;align-items:center;
     margin-bottom:6px;color:var(--muted);font-size:12px}
.hint{color:var(--muted);font-size:12.5px}
.lang{margin-left:auto}
.toast{position:fixed;left:50%;bottom:28px;transform:translateX(-50%);
       background:var(--ink);color:var(--card);padding:8px 16px;border-radius:8px;
       font-size:13px;opacity:0;pointer-events:none;transition:opacity .2s}
</style>
</head>
<body>
<div class="lbl"><span></span>
  <span class="lang"><button id="l-en">English</button> <button id="l-zh">简体中文</button></span>
</div>
<h1 id="t-title"></h1>
<p class="sub" id="t-sub"></p>
<div class="wrap">
  <div class="stage card"><svg id="stage" width="@@W@@" height="@@H@@"></svg>
    <div class="row" id="row-btns">
      <button id="b-reset"></button>
      <button id="b-handles"></button>
      <button id="b-json"></button>
      <label class="chk"><input type="checkbox" id="c-link" checked><span id="t-link"></span></label>
    </div>
    <p class="hint" id="t-hint" style="margin:10px 0 0"></p>
  </div>
  <div class="side">
    <div class="stats">
      <div class="stat"><span id="t-seg"></span><b id="n-seg">0</b></div>
      <div class="stat"><span id="t-anc"></span><b id="n-anc">0</b></div>
      <div class="stat"><span id="t-ctl"></span><b id="n-ctl">0</b></div>
    </div>
    <div><div class="lbl"><span id="t-d"></span></div><pre id="out-d"></pre></div>
    <div>
      <div class="lbl"><span id="t-code"></span><button id="b-copy"></button></div>
      <pre id="out-code"></pre>
    </div>
    <p class="hint" id="t-json"></p>
  </div>
</div>
<div class="toast" id="toast"></div>
<script>
var DATA = @@DATA@@;
var UI = @@UI@@;
var LANG = "@@LANG@@";

var segs = JSON.parse(JSON.stringify(DATA.segments));   // DATA 必须保持原样，"复位"才有东西可回 / keep DATA pristine so Reset has something to restore
var grid = DATA.grid || 0;
var W = DATA.w, H = DATA.h;
var showHandles = true, linkHandles = true, sel = null;
var drag = null;

// "var stage" 之前是**纯逻辑段**：不碰 document / window，可被 Node 直接跑来做跨语言校验。
// 提示默认丢弃，DOM 段再把它接到页面上的 toast / no-op here, wired to the toast further down
var notify = function(msg){};

function ui(key, vars){
  var txt = (UI[LANG] && UI[LANG][key]) || (UI.en && UI.en[key]) || key;
  return txt.replace(/\{(\w+)\}/g, function(m, k){ return vars && (k in vars) ? vars[k] : m; });
}
function num(v){
  v = parseFloat(v);
  if (!isFinite(v)) v = 0;
  return String(Math.round(v * 10000) / 10000);
}
function pt(p){ return num(p[0]) + "," + num(p[1]); }

function toD(){
  var out = [];
  for (var i = 0; i < segs.length; i++){
    var s = segs[i];
    if (!s.cmd) continue;
    if (s.cmd === "M" || s.cmd === "L") out.push(s.cmd + pt(s.end));
    else if (s.cmd === "C") out.push("C" + pt(s.ctrls[0]) + " " + pt(s.ctrls[1]) + " " + pt(s.end));
    else if (s.cmd === "Q") out.push("Q" + pt(s.ctrls[0]) + " " + pt(s.end));
    else if (s.cmd === "A"){
      var q = s.params || [0, 0, 0, 0, 0];
      out.push("A" + num(q[0]) + "," + num(q[1]) + " " + num(q[2]) + " " +
               (q[3] ? 1 : 0) + "," + (q[4] ? 1 : 0) + " " + pt(s.end));
    }
    else if (s.cmd === "Z") out.push("Z");
  }
  return out.join(" ");
}

function buildGroups(){
  var groups = [], ctrls = [], last = null;
  for (var si = 0; si < segs.length; si++){
    var s = segs[si];
    if (s.cmd === "M"){
      last = [["start", si], ["end", si]];
      groups.push(last);
      continue;
    }
    if (last !== null) last.push(["start", si]);
    else { last = [["start", si]]; groups.push(last); }
    for (var k = 0; k < (s.ctrls || []).length; k++) ctrls.push([si, k]);
    if (s.cmd === "Z") last = null;
    else { last = [["end", si]]; groups.push(last); }
  }
  return { anchors: groups, ctrls: ctrls };
}

function applyAnchor(refs, x, y){
  for (var i = 0; i < refs.length; i++){
    var s = segs[refs[i][1]];
    if (refs[i][0] === "start") s.start = [x, y]; else s.end = [x, y];
  }
}
function anchorPos(refs){ var s = segs[refs[0][1]]; return refs[0][0] === "start" ? s.start : s.end; }
function moveAnchor(refs, x, y){
  var old = anchorPos(refs), dx = x - old[0], dy = y - old[1];
  applyAnchor(refs, x, y);
  if (!linkHandles) return;
  for (var j = 0; j < segs.length; j++){
    var g = segs[j];
    if (!g.ctrls || !g.ctrls.length) continue;
    for (var r = 0; r < refs.length; r++){
      if (refs[r][1] !== j) continue;
      if (g.cmd === "Q"){
        if (refs[r][0] === "start") g.ctrls[0] = [g.ctrls[0][0] + dx, g.ctrls[0][1] + dy];
      } else if (g.cmd === "C"){
        var which = refs[r][0] === "start" ? 0 : 1;
        g.ctrls[which] = [g.ctrls[which][0] + dx, g.ctrls[which][1] + dy];
      }
    }
  }
}

function splitSegment(si, t){
  var s = segs[si];
  if (s.cmd === "A"){ notify(ui("arc_no_split")); return false; }
  if (s.cmd !== "L" && s.cmd !== "C" && s.cmd !== "Q") return false;
  t = Math.max(0.02, Math.min(0.98, t));
  var lerp = function(a, b){ return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t]; };
  if (s.cmd === "L"){
    var mid = lerp(s.start, s.end);
    segs[si] = { cmd: "L", start: s.start, end: mid, ctrls: [], params: null };
    segs.splice(si + 1, 0, { cmd: "L", start: mid, end: s.end, ctrls: [], params: null });
  } else if (s.cmd === "C"){
    var q0 = lerp(s.start, s.ctrls[0]), q1 = lerp(s.ctrls[0], s.ctrls[1]),
        q2 = lerp(s.ctrls[1], s.end);
    var r0 = lerp(q0, q1), r1 = lerp(q1, q2), sp = lerp(r0, r1);
    segs[si] = { cmd: "C", start: s.start, end: sp, ctrls: [q0, r0], params: null };
    segs.splice(si + 1, 0, { cmd: "C", start: sp, end: s.end, ctrls: [r1, q2], params: null });
  } else {
    var u0 = lerp(s.start, s.ctrls[0]), u1 = lerp(s.ctrls[0], s.end), sp2 = lerp(u0, u1);
    segs[si] = { cmd: "Q", start: s.start, end: sp2, ctrls: [u0], params: null };
    segs.splice(si + 1, 0, { cmd: "Q", start: sp2, end: s.end, ctrls: [u1], params: null });
  }
  return true;
}

var stage = document.getElementById("stage");
var toast = document.getElementById("toast"), toastTimer = null;
notify = function(msg){
  toast.textContent = msg;
  toast.style.opacity = "1";
  if (toastTimer) clearTimeout(toastTimer);
  toastTimer = setTimeout(function(){ toast.style.opacity = "0"; }, 1800);
};
function draw(){
  var g = buildGroups();
  var d = toD(), s = "";
  if (grid){
    for (var gx = 0; gx <= W; gx += grid)
      s += '<line x1="' + gx + '" y1="0" x2="' + gx + '" y2="' + H + '" stroke="#e6e6ea" stroke-width="1"/>';
    for (var gy = 0; gy <= H; gy += grid)
      s += '<line x1="0" y1="' + gy + '" x2="' + W + '" y2="' + gy + '" stroke="#e6e6ea" stroke-width="1"/>';
  }
  s += '<path class="ps" d="' + d + '" fill="' + DATA.fill +
       '" stroke="' + DATA.stroke + '" stroke-width="' + DATA.strokeWidth +
       '" stroke-linecap="round" stroke-linejoin="round"/>';
  if (showHandles){
    for (var i = 0; i < segs.length; i++){
      var seg = segs[i];
      if (!seg.ctrls || !seg.ctrls.length) continue;
      var pts = [seg.start].concat(seg.ctrls).concat([seg.end]);
      for (var k = 0; k + 1 < pts.length; k++)
        s += '<line x1="' + pts[k][0] + '" y1="' + pts[k][1] + '" x2="' + pts[k + 1][0] +
             '" y2="' + pts[k + 1][1] + '" stroke="#b9c2cf" stroke-width="1"/>';
    }
    for (var ci = 0; ci < g.ctrls.length; ci++){
      var ref = g.ctrls[ci], sg = segs[ref[0]], cp = sg.ctrls[ref[1]];
      var on = sel && sel.kind === "c" && sel.si === ref[0] && sel.ci === ref[1];
      s += '<circle class="ph" data-si="' + ref[0] + '" data-ci="' + ref[1] +
           '" cx="' + cp[0] + '" cy="' + cp[1] + '" r="' + (on ? 6.5 : 5) +
           '" fill="' + (on ? "#000" : DATA.ctrl) + '" stroke="#fff" stroke-width="1.5" style="cursor:grab"/>';
    }
  }
  for (var ai = 0; ai < g.anchors.length; ai++){
    var ap = anchorPos(g.anchors[ai]);
    var on2 = sel && sel.kind === "a" && sel.i === ai;
    s += '<rect class="pa" data-i="' + ai + '" x="' + (ap[0] - 5.5) + '" y="' + (ap[1] - 5.5) +
         '" width="11" height="11" rx="2" fill="' + (on2 ? "#000" : DATA.anchor) +
         '" stroke="#fff" stroke-width="1.5" style="cursor:grab"/>';
  }
  stage.innerHTML = s;
  document.getElementById("n-seg").textContent = segs.filter(function(x){ return x.cmd; }).length;
  document.getElementById("n-anc").textContent = g.anchors.length;
  document.getElementById("n-ctl").textContent = g.ctrls.length;
  document.getElementById("out-d").textContent = d;
  document.getElementById("out-code").textContent =
    'from malight import Malight\n\n' +
    'pen = Malight("curve", width=' + W + ', height=' + H + ')\n' +
    'p = pen.path(fill_color="' + DATA.fill + '", stroke_color="' + DATA.stroke +
    '", stroke_width=' + DATA.strokeWidth + ')\n' +
    'p.set_d("' + d + '")\n' +
    'pen.finish()\n';
}

function groups(){ return buildGroups(); }
function local(e){
  var r = stage.getBoundingClientRect();
  return [(e.clientX - r.left) * W / r.width, (e.clientY - r.top) * H / r.height];
}
stage.addEventListener("pointerdown", function(e){
  var t = e.target;
  if (t.classList.contains("pa")){ sel = { kind: "a", i: +t.dataset.i }; drag = sel; }
  else if (t.classList.contains("ph")){ sel = { kind: "c", si: +t.dataset.si, ci: +t.dataset.ci }; drag = sel; }
  else { sel = null; draw(); return; }
  var p = local(e), cur;
  if (drag.kind === "a") cur = anchorPos(groups().anchors[drag.i]);
  else cur = segs[drag.si].ctrls[drag.ci];
  drag.dx = p[0] - cur[0]; drag.dy = p[1] - cur[1];
  e.preventDefault(); draw();
});
stage.addEventListener("dblclick", function(e){
  var t = e.target;
  if (!t.classList.contains("ps")) return;
  var p = local(e), best = -1, bd = 1e9;
  for (var i = 0; i < segs.length; i++){
    if (!segs[i].cmd || segs[i].cmd === "M" || segs[i].cmd === "Z" || segs[i].cmd === "A") continue;
    var a = segs[i].start, b = segs[i].end;
    var mx = (a[0] + b[0]) / 2, my = (a[1] + b[1]) / 2;
    var dd = (mx - p[0]) * (mx - p[0]) + (my - p[1]) * (my - p[1]);
    if (dd < bd){ bd = dd; best = i; }
  }
  if (best < 0) return;
  sel = null;
  if (splitSegment(best, 0.5)) draw();
});
window.addEventListener("pointermove", function(e){
  if (!drag) return;
  var p = local(e), x = Math.max(-W, Math.min(W * 2, p[0] - drag.dx)),
      y = Math.max(-H, Math.min(H * 2, p[1] - drag.dy));
  if (drag.kind === "a") moveAnchor(groups().anchors[drag.i], x, y);
  else segs[drag.si].ctrls[drag.ci] = [x, y];
  draw();
});
window.addEventListener("pointerup", function(){ drag = null; });

window.addEventListener("keydown", function(e){
  if (!sel) return;
  var step = e.shiftKey ? 10 : 1, dx = 0, dy = 0;
  if (e.key === "ArrowLeft") dx = -step;
  else if (e.key === "ArrowRight") dx = step;
  else if (e.key === "ArrowUp") dy = -step;
  else if (e.key === "ArrowDown") dy = step;
  else return;
  e.preventDefault();
  if (sel.kind === "a"){
    var gp = groups().anchors[sel.i];
    moveAnchor(gp, anchorPos(gp)[0] + dx, anchorPos(gp)[1] + dy);
  } else {
    var c = segs[sel.si].ctrls[sel.ci];
    segs[sel.si].ctrls[sel.ci] = [c[0] + dx, c[1] + dy];
  }
  draw();
});

function exportJSON(){
  var out = [];
  for (var i = 0; i < segs.length; i++){
    var s = segs[i];
    if (!s.cmd) continue;
    out.push({
      cmd: s.cmd,
      start: [parseFloat(s.start[0]), parseFloat(s.start[1])],
      end: [parseFloat(s.end[0]), parseFloat(s.end[1])],
      ctrls: (s.ctrls || []).map(function(c){ return [parseFloat(c[0]), parseFloat(c[1])]; }),
      params: s.params ? s.params.slice() : null
    });
  }
  return { d: toD(), segments: out };
}
document.getElementById("b-json").onclick = function(){
  var blob = new Blob([JSON.stringify(exportJSON(), null, 2)],
                      { type: "application/json" });
  var a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = "points.json";
  a.click();
  setTimeout(function(){ URL.revokeObjectURL(a.href); }, 4000);
};
document.getElementById("b-copy").onclick = function(){
  var b = this, text = document.getElementById("out-code").textContent + "\n";
  var done = function(ok){ b.textContent = ui(ok ? "copied" : "copy_fail");
    setTimeout(function(){ b.textContent = ui("copy"); }, 1400); };
  if (navigator.clipboard && navigator.clipboard.writeText)
    navigator.clipboard.writeText(text).then(function(){ done(true); }, function(){ done(false); });
  else done(false);
};
document.getElementById("b-handles").onclick = function(){
  showHandles = !showHandles;
  this.className = showHandles ? "on" : "";
  draw();
};
document.getElementById("c-link").onchange = function(){ linkHandles = this.checked; };
document.getElementById("b-reset").onclick = function(){
  segs = JSON.parse(JSON.stringify(DATA.segments));
  sel = null; draw();
};
function setLang(code){
  LANG = code;
  document.documentElement.lang = code;
  document.getElementById("t-title").textContent = ui("title");
  document.getElementById("t-sub").textContent = ui("subtitle");
  document.getElementById("t-hint").textContent = ui("hint");
  document.getElementById("t-seg").textContent = ui("segments");
  document.getElementById("t-anc").textContent = ui("anchors");
  document.getElementById("t-ctl").textContent = ui("controls");
  document.getElementById("t-d").textContent = ui("d_label");
  document.getElementById("t-code").textContent = ui("code_label");
  document.getElementById("t-json").textContent = ui("json_hint");
  document.getElementById("t-link").textContent = ui("link_handles");
  document.getElementById("b-copy").textContent = ui("copy");
  document.getElementById("b-reset").textContent = ui("reset");
  document.getElementById("b-handles").textContent = ui("handles");
  document.getElementById("b-json").textContent = ui("json");
  document.getElementById("l-en").className = code === "en" ? "on" : "";
  document.getElementById("l-zh").className = code === "zh" ? "on" : "";
  draw();
}
document.getElementById("l-en").onclick = function(){ setLang("en"); };
document.getElementById("l-zh").onclick = function(){ setLang("zh"); };
setLang(LANG);
</script>
</body>
</html>
"""


# ===========================================================================
# 路径 UI 编辑器 / Path HTML editor
# ===========================================================================
class PathHTMLEditor:
    """
    把一条路径导出成可拖拽的单文件 HTML 编辑器。 / Export a path as a self-contained, draggable HTML editor.

    示例::

        ed = PathHTMLEditor(p)            # p 是 PathElement
        ed.save("edit.html")              # 双击生成的 HTML 就能拖点了
        print(ed.render()[:60])           # 只想拿字符串也可以
    """

    def __init__(self, path=None, d=None, points=None, width=None, height=None,
                 background="#ffffff", stroke_color="#e63946", stroke_width=3,
                 fill_color="none", grid=20, title=None):
        """
        :param path: 要编辑的 PathElement（也可用 d= / points= 二选一）
        :param d: 直接给 d 字符串（如 ``"M20,200 C80,40 180,40 240,200"``）
        :param points: ``PathEditor.to_dict()`` 那种 ``{"segments": [...]}`` 结构
        :param width: 画布宽；缺省时取 path 所属绘图板的宽，再退化为 640
        :param height: 画布高；同上
        :param background: 画布底色（仅影响页面，不影响你导出的 SVG）
        :param stroke_color: 路径描边色（页面预览用，也让生成的代码好看一点）
        :param stroke_width: 路径线宽
        :param fill_color: 填充色，默认 ``"none"``
        :param grid: 网格间距（像素）；``0`` 关闭网格
        :param title: 页面标题；缺省用 i18n 的 ``html.title``

        三个数据源**按 d > points > path 的优先级**取第一个给了的；
        一个都不给会抛 ``ValueError``。
        """
        self.path = path
        self._d_given = d
        self._points = points
        self.width = int(width) if width else self._guess_size()[0]
        self.height = int(height) if height else self._guess_size()[1]
        self.background = background
        self.stroke_color = stroke_color
        self.stroke_width = stroke_width
        self.fill_color = fill_color
        self.grid = int(grid or 0)
        self.title = title
        if path is None and d is None and points is None:
            raise ValueError(t("err.html_no_source"))

    # ---------------------------------------------------------------
    # 取点位模型
    # ---------------------------------------------------------------
    def _guess_size(self):
        """从路径所属绘图板猜画布尺寸；猜不到就用 640x420（内部函数）。"""
        board = getattr(self.path, "board", None) if self.path is not None else None
        w = getattr(board, "width", None)
        h = getattr(board, "height", None)
        return (int(w) if w else 640, int(h) if h else 420)

    def segments(self) -> list:
        """
        当前的线段列表（每次调用重新解析，改过 path 的 d 之后能拿到新的）。 / Segment list, re-parsed on each call so edits to the path show up.

        :return: [PathSegment, ...]
        """
        if self._d_given is not None:
            return parse_path_d(self._d_given)
        if self._points is not None:
            return self._segments_from_points()
        return parse_path_d(self.path.get_d())

    def _segments_from_points(self):
        """把 PathEditor.to_dict() 的 segments 还原成 PathSegment（内部函数）。"""
        from .segment import PathSegment

        out = []
        for item in (self._points or {}).get("segments", []):
            out.append(PathSegment(item["cmd"], item["start"], item["end"],
                                   ctrls=item.get("ctrls") or (),
                                   params=tuple(item["params"])
                                   if item.get("params") else None))
        return out

    def to_dict(self) -> dict:
        """
        转成可 JSON 序列化的数据（结构与 `PathEditor.to_dict()` 一致）。 / The same JSON-ready structure that PathEditor.to_dict returns.

        示例::

            PathHTMLEditor(p).to_dict()["segments"][-1]["end"]
        """
        segs = self.segments()
        return {"d": segments_to_d(segs),
                "segments": [{"cmd": s.cmd,
                              "start": list(s.start),
                              "end": list(s.end),
                              "ctrls": [list(c) for c in s.ctrls],
                              "params": list(s.params) if s.params else None}
                             for s in segs]}

    # ---------------------------------------------------------------
    # 渲染 / 落盘
    # ---------------------------------------------------------------
    def render(self) -> str:
        """
        生成完整的 HTML 文本（自我包含，可直接写盘或塞进任何地方）。 / Build the whole self-contained HTML page as a string.

        :return: HTML 源码

        示例::

            html = PathHTMLEditor(d="M0,0 L100,0").render()
        """
        segs = self.segments()
        body = {"d": segments_to_d(segs),
                "segments": [{"cmd": s.cmd,
                              "start": list(s.start),
                              "end": list(s.end),
                              "ctrls": [list(c) for c in s.ctrls],
                              "params": list(s.params) if s.params else None}
                             for s in segs]}
        data = {
            "w": self.width, "h": self.height, "grid": self.grid,
            "stroke": self.stroke_color, "strokeWidth": self.stroke_width,
            "fill": self.fill_color,
            "d": body["d"],
            "segments": body["segments"],
        }
        title = self.title or t("html.title")
        lang = "zh" if is_chinese() else "en"
        return (_PAGE
                .replace("@@LANG@@", lang)
                .replace("@@TITLE@@", title)
                .replace("@@W@@", str(self.width))
                .replace("@@H@@", str(self.height))
                .replace("@@DATA@@", json.dumps(data, ensure_ascii=False))
                .replace("@@UI@@", json.dumps(_ui_messages(), ensure_ascii=False)))

    def save(self, file) -> str:
        """
        把页面写到磁盘，返回绝对路径。 / Write the page to disk and return its absolute path.

        :param file: 输出文件路径（建议以 .html 结尾）
        :return: 绝对路径

        示例::

            PathHTMLEditor(p).save("output/path_editor.html")
        """
        file = os.path.abspath(file)
        parent = os.path.dirname(file)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(file, "w", encoding="utf-8", newline="\n") as f:
            f.write(self.render())
        print(paint_path(t("html.saved", file=file), file))
        return file

    def __repr__(self):
        """调试用短描述。 / Short debug description."""
        return "<PathHTMLEditor {}x{} {}>".format(
            self.width, self.height, segments_to_d(self.segments())[:40])


# ===========================================================================
# 使用示例
# ===========================================================================
# 在 PyCharm 里点绿色三角直接运行本文件即可；也可命令行：
#     python -m malight.pathkit.htmleditor
# 本示例覆盖 PathHTMLEditor 的全部公开能力：
#     构造（path / d / points 三种来源）/ segments / to_dict / render / save / repr
# 生成的文件在 output/ 下，双击用浏览器打开即可拖点。
# ===========================================================================
if __name__ == "__main__":
    import os

    from malight import Malight, ColorName
    from malight.pathkit import PathEditor, PathHTMLEditor

    _out = os.path.abspath(os.path.join(os.path.dirname(__file__),
                                        "..", "..", "output"))
    os.makedirs(_out, exist_ok=True)

    # -----------------------------------------------------------------
    # 1) 造一条路径：起笔 + 直线 + 三次贝塞尔 + 二次贝塞尔 / 1) Build a path: move, line, cubic and quad curves
    # -----------------------------------------------------------------
    pen = Malight(os.path.join(_out, "demo_path_htmleditor"), width=660, height=430)
    pen.set_background_color(ColorName.WHITESMOKE)
    p = pen.path(fill_color="none", stroke_color=ColorName.DARKSLATEGRAY,
                 stroke_width=3)
    p.move_to(60, 320)
    p.line_to(150, 190)
    p.cubic_to((210, 80), (320, 80), (380, 190))
    p.quad_to((450, 280), (560, 210))

    # -----------------------------------------------------------------
    # 2) 从 PathElement 导出：画布尺寸默认跟随绘图板（660x430） / 2) Export from a PathElement; the canvas follows the board size (660x430)
    # -----------------------------------------------------------------
    ed = PathHTMLEditor(p)
    print("画布尺寸 : / canvas :", ed.width, "x", ed.height)
    print("段数     : / segments :", len(ed.segments()))
    print("d 串     : / d string :", ed.to_dict()["d"][:56], "...")

    # 3) 落盘：双击 output/path_editor.html 就能打开拖点 / 3) Save it: open the file in a browser and start dragging
    ed.save(os.path.join(_out, "path_editor.html"))

    # -----------------------------------------------------------------
    # 4) 只给 d 串也能用（不需要绘图板，适合处理别处拿来的路径） / 4) A bare d string works too, no board needed
    # -----------------------------------------------------------------
    bare = PathHTMLEditor(d="M40,160 C40,40 200,40 200,160 Z", width=260, height=220)
    bare.save(os.path.join(_out, "path_editor_from_d.html"))
    print("从 d 导出 : / from d :", bare)

    # -----------------------------------------------------------------
    # 5) 接着 PathEditor 的进度来：存档 -> 页面里拖 -> 下载 points.json 读回 / 5) Round-trip through JSON: save, drag in the browser, load back
    #    页面下载的 JSON 与 PathEditor.to_dict() 同一套结构，可直接 load_json / the downloaded JSON matches PathEditor.to_dict, ready for load_json
    # -----------------------------------------------------------------
    pe = PathEditor(p)
    pe.move_anchor(1, 160, 170)                    # 先在 Python 里挪一个锚点 / nudge an anchor in Python first
    from_points = PathHTMLEditor(points=pe.to_dict())
    print("点位来源  : / from points :", len(from_points.segments()), "段 / segments")
    print("两条来源  : / same d :", from_points.to_dict()["d"] == pe.to_d())
    from_points.save(os.path.join(_out, "path_editor_from_points.html"))

    # -----------------------------------------------------------------
    # 6) 页面是自我包含的：没有 CDN、没有框架，离线双击即用 / 6) The page is self-contained: no CDN, no framework, works offline
    # -----------------------------------------------------------------
    html = ed.render()
    # 占位符左右各写一份 / write the placeholder on both halves
    # 只写中文半边的话，英文页会取到 "bytes".format(n)，数字被静默吞掉 / otherwise the English page gets "bytes".format(n) and silently loses the number
    _size = len(html.encode("utf-8"))
    print("页面体积  : / page size :", "{:,} 字节 / {:,} bytes".format(_size, _size))
    print("离线可用  : / offline :", "http://" not in html and "https://" not in html)

    pen.finish()
