# -*- coding: utf-8 -*-
"""
模块文档生成器（gen_docs）
==========================

从源码**自动生成**每个模块同目录的双语文档：``xxx.py`` 对应 ``xxx.zh.md``（中文）
与 ``xxx.en.md``（English）。文档跟着代码走，改 API 时顺手改旁边那篇即可。

语言码用 ISO 639-1 的 ``zh`` / ``en``，与 ``malight.i18n`` 的 ``Language.ZH``、
环境变量 ``MALIGHT_LANG=zh`` 保持一致；将来加繁体就是 ``xxx.zh-TW.md``。

文件命名 / File naming:
    ``path.py`` → ``path.zh.md``（中文）+ ``path.en.md``（English）。
    仓库根的 ``README.md`` 沿用平台约定（GitHub/Gitee 只自动渲染这个名字）保留中文，
    英文入口是 ``README.en.md``。

生成内容 / What each page contains:
    1. 语言开关（中文 / English 互切）+ 返回 README；
    2. 模块摘要（中文取自源码文档字符串，英文另见 tools/body_en.py）；
    3. 类与方法清单，签名直接来自源码，说明取自文档字符串的双语摘要；
    4. 该模块 ``__main__`` 里的完整可运行示例（注释与文案按语言各取一半）；
    5. 同级模块导航。

英文页**不出现中文**（语言开关的 ``[简体中文]`` 除外），``--check`` 会逐行校验。

另外会把 ``README.md`` / ``README.en.md`` 中
``<!-- DOCS-INDEX:START -->`` 与 ``<!-- DOCS-INDEX:END -->`` 之间的索引表重建，
保证 README 与模块列表永不脱节。

用法 / Usage::

    python tools/gen_docs.py              # 生成全部文档
    python tools/gen_docs.py --check      # 只检查（CI 用），有缺漏则退出码 1
    python tools/gen_docs.py path.py      # 只生成名字匹配的模块
"""

from __future__ import print_function

import ast
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import bipair                                              # noqa: E402
import body_en as body_en_mod                              # noqa: E402
from gen_previews import PREVIEWS, preview_link            # noqa: E402

CN = re.compile(r"[\u4e00-\u9fff]")
#: 英文页唯一允许出现中文的地方：语言开关的链接文字
SWITCH = re.compile(r"\[\u7b80\u4f53\u4e2d\u6587\]")

#: 不生成文档的文件（包的 __init__.py 只做再导出，页面会是空壳）
SKIP_NAMES = {"__init__.py"}

INDEX_START = "<!-- DOCS-INDEX:START -->"
INDEX_END = "<!-- DOCS-INDEX:END -->"

BANNER_CN = ("<!-- 本文件由 tools/gen_docs.py 从源码自动生成，请勿手改。\n"
             "     要改内容请改同目录的 {src} 里的文档字符串，然后重跑生成器。 -->")
BANNER_EN = ("<!-- Generated by tools/gen_docs.py from the source docstrings.\n"
             "     Do not edit by hand: edit the docstrings in {src} and re-run. -->")


# ===========================================================================
# 基础工具
# ===========================================================================
def read(path):
    """读文本，原样保留行尾（用于要原样写回的 README）。"""
    return io.open(path, encoding="utf-8", newline="").read()


def read_src(path):
    """读源码并统一成 LF —— 否则源码里的 CRLF 会混进生成的文档。"""
    return (io.open(path, encoding="utf-8", newline="").read()
            .replace("\r\n", "\n").replace("\r", "\n"))


def write(path, text):
    io.open(path, "w", encoding="utf-8", newline="").write(text)


def rel(root, path):
    return os.path.relpath(path, root).replace(os.sep, "/")


#: Markdown 会把 ``<clipPath>`` 这类尖括号当 HTML 标签吞掉，转成行内代码
TAG = re.compile(r"</?[A-Za-z][A-Za-z0-9]*(?:\s+[^<>]*)?>")


def _wrap_tag(m):
    raw = m.string
    if m.start() > 0 and raw[m.start() - 1] == "`" and raw[m.end():m.end() + 1] == "`":
        return m.group(0)                     # 已经是行内代码，别套两层
    return "`" + m.group(0) + "`"


def md_text(text):
    """把文档字符串里的 RST / HTML 记号转成安全的 Markdown。"""
    text = text.replace("``", "`")
    return TAG.sub(_wrap_tag, text)


#: RST 网格表的行分隔线，如 ``=======  ======``
GRID_SEP = re.compile(r"^[ \t]*=+([ \t]+=+)+[ \t]*$")
#: 以 ``::`` 结尾的行 = RST 字面块引导（``示例::``、``用法::``）
LITERAL_HEAD = re.compile(r"^(.*?)::[ \t]*$")


def _dedent(lines):
    """去掉一段文本的公共缩进。"""
    indents = [len(l) - len(l.lstrip()) for l in lines if l.strip()]
    cut = min(indents) if indents else 0
    return [l[cut:] if len(l) >= cut else l.lstrip() for l in lines]


def _trim(lines):
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


def _take_indented(lines, i):
    """从 ``i`` 起吞掉一个「缩进块」（先跳过空行），返回 ``(块内容, 下一个下标)``。"""
    while i < len(lines) and not lines[i].strip():
        i += 1
    block = []
    while i < len(lines) and (not lines[i].strip() or lines[i][:1] in " \t"):
        block.append(lines[i])
        i += 1
    return _trim(block), i


def _take_table(lines, i):
    """从 ``i`` 起吞掉 RST 网格表：连续非空行，遇空行结束。"""
    block = []
    while i < len(lines) and lines[i].strip():
        block.append(lines[i])
        i += 1
    return _trim(block), i


def _split_cells(line):
    """把 RST 网格表的一行按「两个以上空格」切成单元格。"""
    return [c.strip() for c in re.split(r"\s{2,}", line.strip())]


def grid_to_md(block):
    """
    尝试把 RST 网格表转成 Markdown 表格（首行当表头）。

    :return: Markdown 表格文本；形状不规整（列数对不齐）时返回 ``None``
    """
    rows = [_split_cells(l) for l in block if not GRID_SEP.match(l)]
    rows = [r for r in rows if any(r)]
    if len(rows) < 2:
        return None
    ncols = len(rows[0])
    if ncols < 2 or any(len(r) != ncols for r in rows):
        return None
    head, body = rows[0], rows[1:]
    out = ["| " + " | ".join(md_text(c) for c in head) + " |",
           "|" + "---|" * ncols]
    for r in body:
        out.append("| " + " | ".join(md_text(c).replace("|", r"\|") for c in r) + " |")
    return out


def rst_to_md(text):
    """
    把源码文档字符串里的 RST 小记号转成 Markdown 正文。

    处理三件事 / Handles three things:
      * `` ``code`` `` → `` `code` ``；
      * ``示例::`` / ``用法::`` 后面的缩进块 → ```` ```python ```` 代码块；
      * RST 网格表（``====`` 分隔行）→ ```` ```text ```` 等宽块，保住列对齐。
    """
    lines = text.split("\n")
    out, i = [], 0
    while i < len(lines):
        line = lines[i]
        head = LITERAL_HEAD.match(line)
        if head and not GRID_SEP.match(line):
            block, nxt = _take_indented(lines, i + 1)
            if block:
                title = md_text(head.group(1)).strip()
                if title:
                    out.append(title)
                    out.append("")
                lang = "python" if ("示例" in title or "用法" in title) else "text"
                out.append("```" + lang)
                out.extend(_dedent(block))
                out.append("```")
                out.append("")
                i = nxt
                continue
        if GRID_SEP.match(line):
            block, nxt = _take_table(lines, i)
            table = grid_to_md(block)
            if table:
                out.extend(table)
                out.append("")
            else:
                out.append("```text")
                out.extend(md_text(l) for l in _dedent(block))
                out.append("```")
                out.append("")
            i = nxt
            continue
        out.append(md_text(line))
        i += 1
    return "\n".join(out)


def split_bilingual(text):
    """
    拆开「中文。 / English.」形式的摘要。

    :return: ``(中文, 英文)``；没有英文部分时第二项为空串
    """
    if "。 / " in text:
        cn, en = text.split("。 / ", 1)
        return cn.strip() + "。", en.strip()
    return text.strip(), ""


#: 摘要里若混进了 ``示例::`` 一类的块引导，从这里截断
EXAMPLE_MARK = re.compile(r"\s*(?:示例|用法|例|Example|Usage|Examples)::")


def first_paragraph(doc):
    """取文档字符串首段（折叠成一行）；遇到 ``::`` 块引导则截断。"""
    if not doc:
        return ""
    head = []
    for line in doc.strip().splitlines():
        s = line.strip()
        if not s or s.endswith("::"):
            break
        head.append(s)
    if not head:
        return ""
    text = " ".join(" ".join(head).split())
    mark = EXAMPLE_MARK.search(text)
    if mark:
        text = text[:mark.start()].strip()
    return text


def module_doc_parts(doc):
    """
    拆解模块文档字符串。

    :return: ``(中文标题, 英文摘要, 中文正文)``
    """
    if not doc:
        return "", "", ""
    lines = [l.rstrip() for l in doc.strip().splitlines()]
    title, english, idx = lines[0].strip(), "", 1
    if "。 / " in title:
        cn_part, english = title.split("。 / ", 1)
        title, english = cn_part + "。", english.strip()
    elif " / " in title:
        title, english = [x.strip() for x in title.split(" / ", 1)]
    elif len(lines) > 1 and len(lines[1].strip()) >= 4 and set(lines[1].strip()) == {"="}:
        idx = 2
        while idx < len(lines) and not lines[idx].strip():
            idx += 1
        if idx < len(lines):
            english = lines[idx].strip()
            idx += 1
    body = "\n".join(lines[idx:]).strip()
    return title, english, body


# ===========================================================================
# 源码解析
# ===========================================================================
def format_signature(node):
    """把函数签名渲染成一行紧凑文本（不含 self，超长默认值省略）。"""
    args = node.args
    parts, positional = [], list(getattr(args, "posonlyargs", [])) + list(args.args)
    defaults = list(args.defaults)
    pad = len(positional) - len(defaults)
    for i, a in enumerate(positional):
        if a.arg in ("self", "cls"):
            continue
        if i >= pad:
            default = ast.unparse(defaults[i - pad]) if hasattr(ast, "unparse") \
                else "…"
            default = " ".join(str(default).split())
            if len(default) > 14:
                default = default[:11] + "…"
            parts.append("{}={}".format(a.arg, default))
        else:
            parts.append(a.arg)
    if args.vararg:
        parts.append("*" + args.vararg.arg)
    elif args.kwonlyargs:
        parts.append("*")
    for a, d in zip(args.kwonlyargs, args.kw_defaults):
        parts.append(a.arg if d is None else "{}={}".format(a.arg, "…"))
    if args.kwarg:
        parts.append("**" + args.kwarg.arg)
    return "{}({})".format(node.name, ", ".join(parts))


def collect_module(tree):
    """
    从一个模块 AST 里收集顶层函数、类与类方法。

    :return: ``(functions, classes)``，均为按源码顺序排列的列表
    """
    functions, classes = [], []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
            functions.append(node)
        elif isinstance(node, ast.ClassDef):
            members, props = [], []
            for sub in node.body:
                if not isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                if sub.name.startswith("_"):
                    continue
                is_prop = any(
                    (isinstance(d, ast.Name) and d.id == "property")
                    or (isinstance(d, ast.Attribute) and d.attr == "setter")
                    for d in sub.decorator_list)
                if is_prop:
                    props.append(sub)
                else:
                    members.append(sub)
            classes.append((node, members, props))
    return functions, classes


def extract_example(src):
    """取出 ``if __name__ == "__main__":`` 之后的示例代码。"""
    marker = 'if __name__ == "__main__":'
    idx = src.find(marker)
    return src[idx:].rstrip() + "\n" if idx >= 0 else ""


# ===========================================================================
# 页面渲染
# ===========================================================================
def render_api_cn(functions, classes):
    """渲染中文页的 API 清单。"""
    out = []
    if functions:
        out.append("### 函数\n")
        out.append("| 函数 | 说明 |")
        out.append("|---|---|")
        for node in functions:
            cn, _ = split_bilingual(first_paragraph(ast.get_docstring(node)))
            out.append("| `{}` | {} |".format(node.name, md_text(cn).replace("|", r"\|")))
        out.append("")
    for node, members, props in classes:
        cn, _ = split_bilingual(first_paragraph(ast.get_docstring(node)))
        out.append("### `{}`\n".format(node.name))
        if cn:
            out.append(md_text(cn) + "\n")
        rows = []
        for sub in members:
            cn2, _ = split_bilingual(first_paragraph(ast.get_docstring(sub)))
            rows.append(("`{}`".format(format_signature(sub)), cn2))
        for sub in props:
            cn2, _ = split_bilingual(first_paragraph(ast.get_docstring(sub)))
            rows.append(("`{}`（属性）".format(sub.name), cn2))
        if rows:
            out.append("| 方法 | 说明 |")
            out.append("|---|---|")
            for sig, desc in rows:
                out.append("| {} | {} |".format(sig, md_text(desc).replace("|", r"\|")))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_api_en(functions, classes):
    """
    渲染英文页的 API 清单。

    只输出英文摘要；没有英文时留空（由 ``--check`` 的「英文页纯度」校验兜住），
    绝不回退显示中文 —— 那会让英文读者看到半页中文。
    """
    def en_of(node):
        _cn, en = split_bilingual(first_paragraph(ast.get_docstring(node)))
        return md_text(en)

    out = []
    if functions:
        out.append("### Functions\n")
        out.append("| Function | Description |")
        out.append("|---|---|")
        for node in functions:
            out.append("| `{}` | {} |".format(node.name, en_of(node).replace("|", r"\|")))
        out.append("")
    for node, members, props in classes:
        out.append("### `{}`\n".format(node.name))
        desc = en_of(node)
        if desc:
            out.append(desc + "\n")
        rows = []
        for sub in members:
            rows.append(("`{}`".format(format_signature(sub)), en_of(sub)))
        for sub in props:
            rows.append(("`{}` (property)".format(sub.name), en_of(sub)))
        if rows:
            out.append("| Method | Description |")
            out.append("|---|---|")
            for sig, d in rows:
                out.append("| {} | {} |".format(sig, d.replace("|", r"\|")))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_page(ctx, lang):
    """:param lang: ``"cn"`` 或 ``"en"``"""
    cn = lang == "cn"
    suffix = ".zh.md" if cn else ".en.md"
    name = ctx["name"]

    head = ["# {}.py".format(name)]
    head.append("")
    switch = ("**简体中文** ｜ [English]({other})" if cn
              else "[简体中文]({other}) ｜ **English**")
    head.append(" ｜ ".join([
        switch.format(other=name + (".en.md" if cn else ".zh.md")),
        "[← 返回 README]({})".format(ctx["readme"]) if cn
        else "[← Back to README]({})".format(ctx["readme_en"]),
    ]))
    head.append("")

    if cn:
        head.append(ctx["title"] or name)
        head.append("")
        if ctx["body"]:
            head.append(ctx["body"])
            head.append("")
    else:
        head.append(ctx["english"] or ctx["title"] or name)
        head.append("")
        if ctx["body_en"]:
            head.append(ctx["body_en"])
            head.append("")

    # 效果预览图（集中在仓库根 assets/images/，由 tools/gen_previews.py 生成；
    # 中英两页共用同一张，所以图里的标签是英文）。
    # 放在模块说明之后、API 清单之前 —— 先让读者看到效果，再看方法列表。
    preview = PREVIEWS.get(ctx["src"])
    if preview:
        head.append("![{}]({})".format(preview[1] if cn else preview[2],
                                       preview_link(ctx["src"], preview[0])))
        head.append("")

    api = render_api_cn(*ctx["api"]) if cn else render_api_en(*ctx["api"])
    head.append("---")
    head.append("")
    head.append("## 类与方法" if cn else "## Classes and methods")
    head.append("")
    head.append(api)

    if ctx["example"]:
        head.append("---")
        head.append("")
        head.append("## 完整示例" if cn else "## Full example")
        head.append("")
        head.append("在 PyCharm 里点绿色三角直接运行，或命令行：`python {}`"
                    if cn else
                    "Run it directly in PyCharm, or from the command line: `python {}`")
        head[-1] = head[-1].format(ctx["src"])
        head.append("")
        head.append("```python")
        head.append(bipair.trim_block(ctx["example"].rstrip(), lang))
        head.append("```")
        head.append("")

    if ctx["siblings"]:
        head.append("---")
        head.append("")
        head.append("## 同级模块" if cn else "## Sibling modules")
        head.append("")
        head.append(" ｜ ".join("[{}]({}{})".format(s, s, suffix)
                               for s in ctx["siblings"]))
        head.append("")

    banner = (BANNER_CN if cn else BANNER_EN).format(src=os.path.basename(ctx["src"]))
    return banner + "\n\n" + "\n".join(head).rstrip() + "\n"


def purity_problems(text):
    """
    英文页里不该出现中文，只有语言开关的 ``[简体中文]`` 例外。

    :return: ``[(行号, 行内容), ...]``
    """
    bad = []
    for no, line in enumerate(text.split("\n"), 1):
        if not CN.search(line) or SWITCH.search(line):
            continue
        bad.append((no, line.strip()[:80]))
    return bad


# ===========================================================================
# 主流程
# ===========================================================================
def gather_modules():
    """收集所有要生成文档的模块。"""
    modules = []
    for root, dirs, names in os.walk(os.path.join(ROOT, "malight")):
        dirs[:] = [d for d in dirs if d != "__pycache__"]
        for n in sorted(names):
            if not n.endswith(".py"):
                continue
            path = os.path.join(root, n)
            key = rel(ROOT, path)
            if n in SKIP_NAMES or key in SKIP_NAMES:
                continue
            modules.append(path)
    return sorted(modules)


def build_context(path, sibling_names):
    src = read_src(path)
    tree = ast.parse(src)
    doc = ast.get_docstring(tree)
    title, english, body = module_doc_parts(doc)
    name = os.path.basename(path)[:-3]
    doc_dir = os.path.dirname(path)
    up = os.path.relpath(ROOT, doc_dir).replace(os.sep, "/")
    functions, classes = collect_module(tree)
    siblings = [s for s in sibling_names if s != name]
    key = rel(ROOT, path)
    return {
        "src": key,
        "name": name,
        "title": md_text(title) or name,
        "en_title": md_text(english),
        "english": md_text(english),
        "body": rst_to_md(body),
        # 英文正文来自 tools/body_en.py（中文正文一变，那边的指纹检查就会报过期）
        "body_en": body_en_mod.BODY_EN.get(key, ""),
        "api": (functions, classes),
        "example": extract_example(src),
        "readme": up + "/README.md",
        "readme_en": up + "/README.en.md",
        "siblings": siblings,
    }


def write_index(modules_info):
    """重建 README 里两个标记之间的模块索引表。"""
    groups = {}
    for doc_base, name, title, en_title in modules_info:
        parts = doc_base.split("/")
        group = "/".join(parts[:2]) if len(parts) > 2 else "malight"
        groups.setdefault(group, []).append((name, doc_base, title, en_title))

    touches = 0
    for readme, lang in (("README.md", "cn"), ("README.en.md", "en")):
        path = os.path.join(ROOT, readme)
        if not os.path.isfile(path):
            continue
        text = read(path)
        if INDEX_START not in text or INDEX_END not in text:
            continue
        blocks = []
        for group in sorted(groups):
            rows = groups[group]
            if group == "malight":
                blocks.append("### malight（顶层模块）"
                              if lang == "cn" else "### malight (top-level)")
            else:
                blocks.append("### {}".format(group))
            blocks.append("")
            blocks.append("| 模块 / Module | 说明 / Description |" if lang == "cn"
                          else "| Module | Description |")
            blocks.append("|---|---|")
            for name, doc_base, title, en_title in rows:
                link = "{}.zh.md".format(doc_base) if lang == "cn" \
                    else "{}.en.md".format(doc_base)
                desc = title if lang == "cn" else (en_title or title)
                blocks.append("| [{}]({}) | {} |".format(name, link, desc))
            blocks.append("")
        new = INDEX_START + "\n" + "\n".join(blocks).rstrip() + "\n" + INDEX_END
        text = re.sub(re.escape(INDEX_START) + r".*?" + re.escape(INDEX_END),
                      lambda _m: new, text, flags=re.S)
        write(path, text)
        touches += 1
    return touches


def main(argv):
    check = "--check" in argv
    filters = [a for a in argv if not a.startswith("--")]
    modules = gather_modules()
    by_dir = {}
    for path in modules:
        by_dir.setdefault(os.path.dirname(path), []).append(
            os.path.basename(path)[:-3])

    written, info, dirty = 0, [], []
    for path in modules:
        name = os.path.basename(path)[:-3]
        if filters and not any(f in name or f in path for f in filters):
            continue
        ctx = build_context(path, sorted(by_dir[os.path.dirname(path)]))
        for lang, suffix in (("cn", ".zh.md"), ("en", ".en.md")):
            target = os.path.join(os.path.dirname(path), name + suffix)
            text = render_page(ctx, lang)
            if lang == "en":
                bad = purity_problems(text)
                if bad:
                    dirty.append((rel(ROOT, target), bad))
            if check:
                old = read(target) if os.path.isfile(target) else None
                if old != text:
                    print("过期 / STALE: %s" % rel(ROOT, target))
                    written += 1
            else:
                write(target, text)
                written += 1
        info.append((ctx["src"][:-3], name, ctx["title"], ctx["en_title"]))

    if not check:
        write_index(info)

    for target, bad in dirty:
        print("英文页出现中文 / CJK in English page: %s" % target)
        for no, line in bad[:5]:
            print("    L%-4d %s" % (no, line))
    if dirty:
        print("（英文页只允许语言开关里的 [简体中文]；正文译文放 tools/body_en.py，"
              "示例注释与文案放 tools/code_en.py）")

    print("%s %d 个文档" % ("需重新生成" if check else "已生成", written))
    return 1 if ((check and written) or dirty) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
