# -*- coding: utf-8 -*-
"""
PyPI 说明页生成（pypi_readme）
===============================

PyPI 只渲染**一份** README，而且它不在仓库里 —— 相对链接（``malight/x.en.md``、
``README.md``）在 PyPI 上全是 404。本脚本从 ``README.en.md`` 生成
``README.pypi.md``：

* ``pyproject.toml`` 的 ``[project.urls] Homepage`` 填了真实仓库地址时，
  相对链接会被改写成 ``{Homepage}/blob/main/<路径>`` 的绝对链接；
* 还没填仓库地址时，相对链接退化成**纯文本**（不加超链接），保证 PyPI 页面上
  不会出现点不开的死链；顶部的语言开关行同时**整行去掉**（PyPI 只有这一份
  README，没有"切语言"可谈，留着只会变成一行点不动的 ``简体中文``）；
* 填好 Homepage 后重跑本脚本即可，开关行会自动回来并指向仓库里的中文 README。

``pyproject.toml`` 的 ``readme`` 指向生成物 ``README.pypi.md``。

Generates the single README that PyPI renders from ``README.en.md``: relative links
become absolute once ``[project.urls] Homepage`` is set, and degrade to plain text
until then, so the PyPI page never shows a dead link.

用法 / Usage::

    python tools/pypi_readme.py           # 生成 README.pypi.md
    python tools/pypi_readme.py --check   # 与生成物不一致时退出码 1（CI 用）
"""

from __future__ import print_function

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SOURCE = "README.en.md"
TARGET = "README.pypi.md"
PYPROJECT = "pyproject.toml"

BANNER = ("<!-- Generated by tools/pypi_readme.py from {src} for PyPI.\n"
          "     Do not edit by hand: edit {src} (or fix the module pages) and re-run. -->")

#: ``[text](relative/path.md)``；(?!https?://) 挡住已经是绝对地址的链接
LINK = re.compile(r"\[([^\]]+)\]\((?!/)([^)\s]+)\)")

#: README 顶部的语言开关行，形如 ``[简体中文](README.md) ｜ **English**``
#: （用 ``\uXXXX`` 写中文，脚本本身保持纯 ASCII，免得被当成乱码改坏）
#: 末尾的 ``\n\n?`` 顺手吃掉它后面那个空行，免得删完标题下留两个空行。
SWITCH_LINE = re.compile(r"(?m)^\[\u7b80\u4f53\u4e2d\u6587\]\([^)]*\)[^\n]*\n\n?")


def read(path):
    return io.open(path, encoding="utf-8", newline="").read()


def write(path, text):
    io.open(path, "w", encoding="utf-8", newline="").write(text)


def homepage():
    """从 pyproject.toml 里取 Homepage；没填（或仍是占位）时返回 None。"""
    path = os.path.join(ROOT, PYPROJECT)
    if not os.path.isfile(path):
        return None
    text = read(path)
    block = re.search(r"^\[project\.urls\][^\[]*", text, re.M | re.S)
    if not block:
        return None
    found = re.search(r'^\s*Homepage\s*=\s*"([^"]+)"', block.group(0), re.M)
    if not found:
        return None
    url = found.group(1).strip().rstrip("/")
    if not url.startswith("http") or "<" in url or "yourname" in url:
        return None                       # 占位符，当作没填
    return url


def render():
    """生成 PyPI 说明页文本。"""
    text = read(os.path.join(ROOT, SOURCE))
    home = homepage()

    def repl(match):
        label, link = match.group(1), match.group(2)
        if link.startswith(("http", "mailto", "#")):
            return match.group(0)
        if home is None:
            return "`%s`" % label         # 没地址：退化成纯文本，避免死链
        return "[%s](%s/blob/main/%s)" % (label, home, link.lstrip("./"))

    if home is None:
        # 没填仓库地址时，语言开关那行会退化成 `` `简体中文` `` 这种点不动的死文字，
        # 而 PyPI 页面本来也只有这一份 README、没有"切语言"可谈 —— 整行去掉更干净。
        # 填好 Homepage 后链接会变成指向仓库中文 README 的绝对地址，这行就保留。
        #
        # 注意：必须在 LINK.sub **之前**处理 —— 那一步会把 ``[简体中文](README.md)``
        # 换成 `` `简体中文` ``，之后这行就再也匹配不上了（这个顺序错过一次）。
        text = SWITCH_LINE.sub("", text)

    body = LINK.sub(repl, text)
    return BANNER.format(src=SOURCE) + "\n\n" + body


def main(argv):
    check = "--check" in argv
    text = render()
    target = os.path.join(ROOT, TARGET)
    old = read(target) if os.path.isfile(target) else None

    home = homepage()
    if home is None:
        print("提示：[project.urls] Homepage 还没填真实仓库地址，"
              "PyPI 页里的相对链接已退化成纯文本（不会 404）。")
    else:
        print("Homepage = %s（相对链接已改写成绝对链接）" % home)

    if check:
        if old == text:
            print("PyPI 说明页与 README.en.md 一致")
            return 0
        print("过期 / STALE: %s（重跑 python tools/pypi_readme.py）" % TARGET)
        return 1
    write(target, text)
    print("已生成 %s（%d 字节）" % (TARGET, len(text.encode("utf-8"))))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
